local Config = {
    Debug = false,
    Farming = {
        AutoScrap = false,
        ScrapRadius = 0,
        ScrapDelay = 0.25,
        ScrapPriority = "Nearest",
        ScrapWhitelist = {},
        ScrapBlacklist = {},
        TargetTimeout = 20,
        StuckTimeout = 3,
        PathRetries = 2,
        AutoItems = false,
        ItemRadius = 0,
        ItemCategories = {},
        ItemWhitelist = {},
        ItemBlacklist = {},
        AutoFuelFarm = false,
        FuelReserve = 5,
        AutoPickup = false,
        PickupRadius = 25,
        PickupDelay = 0.2,
        AllItems = true,
        PickupWhitelist = {},
        PickupBlacklist = {},
        PickupCategories = {},
    },
    Generator = {
        AutoFuel = false,
        FuelBelow = 50,
        FuelUntil = 90,
        EmergencyFuel = 20,
        FuelRadius = 0,
        FuelPriority = { "Nuclear Fuel", "Refined Fuel", "Fuel" },
    },
    Combat = {
        KillAura = false,
        Range = 7,
        AttackDelay = 0.4,
        Priority = "Nearest",
        BossPriority = true,
        AutoEquip = false,
        PauseFarming = true,
        TargetIndicator = true,
    },
    Survival = {
        AutoHeal = false,
        HealBelow = 45,
        AutoEat = false,
        EatBelow = 35,
        AutoDrink = false,
        DrinkBelow = 35,
        AutoBandage = false,
        EmergencyHealth = 20,
    },
    Storage = {
        Enabled = false,
        Categories = { Resource = true, Scrap = true, Fuel = true },
        Keep = {},
        Minimum = {},
        ScrapReserve = 20,
        FuelReserve = 5,
        OnlyWhenFull = false,
    },
    Repair = {
        Enabled = false,
        Radius = 30,
        Rate = 1,
        Priority = "LowestHealth",
        Emergency = false,
        EmergencyBelow = 20,
    },
    Player = {
        AutoSprint = false,
        InfiniteJump = false,
        Noclip = false,
        Fly = false,
        FlySpeed = 60,
        WalkSpeed = 16,
        SprintSpeed = 24,
        JumpPower = 50,
        OverrideMovement = false,
        BunnyHop = false,
    },
    Interface = {
        MenuKey = "RightShift",
        Accent = { 145, 90, 255 },
        NotificationSide = "Right",
        Widget = true,
        WidgetOpacity = 0.92,
        WidgetCollapsed = false,
    },
    Visuals = {
        MaxDistance = 0,
        Fullbright = false,
        RemoveFog = false,
        TextSize = 12,
        FillTransparency = 0.75,
        OutlineTransparency = 0,
        Categories = {},
    },
    Teleports = { Saved = {}, SelectedPlayer = "" },
}
for _, name in ipairs({
    "Enemy",
    "Player",
    "Gun",
    "Melee",
    "Medical",
    "Armor",
    "Food",
    "Resource",
    "Scrap",
    "Fuel",
    "Ability",
    "Ammo",
    "Structures",
    "Consumables",
    "Backpacks",
    "MiscItems",
    "Structure",
    "Generator",
    "Chest",
}) do
    Config.Visuals.Categories[name] = {
        Enabled = false,
        Highlight = true,
        Name = true,
        Distance = true,
        Health = true,
        Color = { 145, 90, 255 },
        MaxDistance = 0,
    }
end
return Config
