local Panel = {}
function Panel.Build(ui, tab, h)
    local section
    section = ui:Section(tab, "Scrap grinding")
    ui:Toggle(section, "Auto Grind Scrap", "Farming.AutoScrap")
    ui:Choice(section, "Target priority", "Farming.ScrapPriority", { "Nearest", "Value" })
    ui:Number(section, "Search radius (0 = unlimited)", "Farming.ScrapRadius", 0, 1000000)
    ui:Number(section, "Interaction delay", "Farming.ScrapDelay", 0.1, 10)
    ui:Number(section, "Target timeout", "Farming.TargetTimeout", 3, 120)
    ui:Number(section, "Stuck timeout", "Farming.StuckTimeout", 1, 20)
    ui:Number(section, "Path retries", "Farming.PathRetries", 0, 10)
    ui:Filter(section, "ScrapWhitelist", "Farming.ScrapWhitelist", false)
    ui:Filter(section, "ScrapBlacklist", "Farming.ScrapBlacklist", false)
    section = ui:Section(tab, "Item and fuel farming")
    ui:Toggle(section, "Auto Item Farm", "Farming.AutoItems")
    ui:Number(section, "Item radius (0 = unlimited)", "Farming.ItemRadius", 0, 1000000)
    ui:Filter(section, "ItemCategories", "Farming.ItemCategories", true)
    ui:Filter(section, "Item names (empty = all)", "Farming.ItemWhitelist", false)
    ui:Filter(section, "Excluded items", "Farming.ItemBlacklist", false)
    ui:Toggle(section, "Build fuel reserve", "Farming.AutoFuelFarm")
    ui:Number(section, "Fuel reserve", "Farming.FuelReserve", 0, 1000)
    section = ui:Section(tab, "Pickup")
    ui:Toggle(section, "Auto Pickup", "Farming.AutoPickup")
    ui:Label(section, "Pickup status", function()
        return h.Features.AutoPickup and h.Features.AutoPickup.Status or "Disabled"
    end)
    ui:Toggle(section, "All categories", "Farming.AllItems")
    ui:Number(section, "Pickup radius (0 = unlimited)", "Farming.PickupRadius", 0, 1000000)
    ui:Number(section, "Pickup delay", "Farming.PickupDelay", 0.1, 10)
    ui:Filter(section, "PickupWhitelist", "Farming.PickupWhitelist", false)
    ui:Filter(section, "PickupBlacklist", "Farming.PickupBlacklist", false)
    ui:Filter(section, "PickupCategories", "Farming.PickupCategories", true)
    section = ui:Section(tab, "Storage")
    ui:Toggle(section, "Auto Store", "Storage.Enabled", "StoreItem")
    ui:Toggle(section, "Only when inventory full", "Storage.OnlyWhenFull")
    ui:Filter(section, "Categories", "Storage.Categories", true)
    ui:Filter(section, "Keep", "Storage.Keep", false)
    ui:JSON(section, "Minimum quantities", "Storage.Minimum")
    ui:Number(section, "Keep scrap", "Storage.ScrapReserve", 0, 10000)
    ui:Number(section, "Keep fuel per type", "Storage.FuelReserve", 0, 1000)
end
return Panel
