local Panel = {}
function Panel.Build(ui, tab, h)
    local section
    section = ui:Section(tab, "Scrap grinding")
    ui:Toggle(section, "Auto Grind Scrap", "Farming.AutoScrap")
    ui:Choice(section, "Target priority", "Farming.ScrapPriority", { "Nearest", "Value" })
    ui:Number(section, "Search radius", "Farming.ScrapRadius", 5, 5000)
    ui:Number(section, "Interaction delay", "Farming.ScrapDelay", 0.1, 10)
    ui:Number(section, "Target timeout", "Farming.TargetTimeout", 3, 120)
    ui:Number(section, "Stuck timeout", "Farming.StuckTimeout", 1, 20)
    ui:Number(section, "Path retries", "Farming.PathRetries", 0, 10)
    ui:JSON(section, "Whitelist (JSON name: true)", "Farming.ScrapWhitelist")
    ui:JSON(section, "Blacklist (JSON name: true)", "Farming.ScrapBlacklist")
    section = ui:Section(tab, "Item and fuel farming")
    ui:Toggle(section, "Auto Item Farm", "Farming.AutoItems")
    ui:Number(section, "Item radius", "Farming.ItemRadius", 5, 5000)
    ui:JSON(section, "Item categories", "Farming.ItemCategories")
    ui:Toggle(section, "Build fuel reserve", "Farming.AutoFuelFarm")
    ui:Number(section, "Fuel reserve", "Farming.FuelReserve", 0, 1000)
    section = ui:Section(tab, "Pickup")
    ui:Toggle(section, "Auto Pickup", "Farming.AutoPickup")
    ui:Toggle(section, "All categories", "Farming.AllItems")
    ui:Number(section, "Pickup radius", "Farming.PickupRadius", 1, 100)
    ui:Number(section, "Pickup delay", "Farming.PickupDelay", 0.1, 10)
    ui:JSON(section, "Whitelist", "Farming.PickupWhitelist")
    ui:JSON(section, "Blacklist", "Farming.PickupBlacklist")
    ui:JSON(section, "Category filters", "Farming.PickupCategories")
    section = ui:Section(tab, "Storage")
    ui:Toggle(section, "Auto Store", "Storage.Enabled")
    ui:Toggle(section, "Only when inventory full", "Storage.OnlyWhenFull")
    ui:JSON(section, "Categories", "Storage.Categories")
    ui:JSON(section, "Keep items", "Storage.Keep")
    ui:JSON(section, "Minimum quantities", "Storage.Minimum")
    ui:Number(section, "Keep scrap", "Storage.ScrapReserve", 0, 10000)
    ui:Number(section, "Keep fuel per type", "Storage.FuelReserve", 0, 1000)
end
return Panel
